package json.java21.jsonpath.codegen;

import jdk.sandbox.java.util.json.*;
import java.util.ArrayList;
import java.util.List;
import java.util.function.BiConsumer;

/// Runtime helper for recursive descent operations in generated bytecode.
///
/// Recursive descent (`..property`, `..*`) cannot be fully inlined because
/// the recursion depth is unknown at compile time. This helper provides
/// the DFS traversal that collects all descendant nodes matching a criterion.
public final class RecursiveDescentHelper {

    private RecursiveDescentHelper() {}

    /// Collects all descendant values of a property name from anywhere in the tree.
    ///
    /// @param current the current node to search from
    /// @param name the property name to find
    /// @param results the list to add matched values to
    public static void findProperty(JsonValue current, String name, List<JsonValue> results) {
        // Check current level
        if (current instanceof JsonObject obj) {
            final var members = obj.members();
            final var value = members.get(name);
            if (value != null) {
                results.add(value);
            }
            // Recurse into all children
            for (final var child : members.values()) {
                findProperty(child, name, results);
            }
        } else if (current instanceof JsonArray arr) {
            for (final var element : arr.elements()) {
                findProperty(element, name, results);
            }
        }
    }

    /// Collects all descendant values (wildcard) from anywhere in the tree.
    ///
    /// @param current the current node to search from
    /// @param results the list to add all values to
    public static void findAll(JsonValue current, List<JsonValue> results) {
        if (current instanceof JsonObject obj) {
            for (final var child : obj.members().values()) {
                results.add(child);
                findAll(child, results);
            }
        } else if (current instanceof JsonArray arr) {
            for (final var element : arr.elements()) {
                results.add(element);
                findAll(element, results);
            }
        }
    }
}
