package json.java21.jtd.codegen;

import jdk.incubator.java.util.json.JsonValue;
import json.java21.jtd.JtdValidationResult;

import java.util.Objects;

/// Functional interface for validating a JSON instance against a JTD schema
/// using bytecode-generated validators.
///
/// Requires JDK 24+ at build time (ClassFile API, JEP 484).
/// Generated bytecode targets Java 21 (classfile version 65) so it runs on any JDK 21+ runtime.
///
/// For the interpreter-based validator (always available, JDK 21+), see
/// {@code json.java21.jtd.JtdValidator} in the {@code json-java21-jtd} module.
///
/// Obtain an instance via:
/// - [#compileGenerated(JsonValue)] -- bytecode-generated path, requires JDK 24+.
@FunctionalInterface
public interface JtdValidator {

  /// Validates an instance against the compiled schema.
  ///
  /// @param instance the JSON value to validate
  /// @return the validation result with RFC 8927 error pairs
  JtdValidationResult validate(JsonValue instance);

  /// Compiles a JTD schema into a bytecode-generated validator.
  /// Requires JDK 24+ (ClassFile API). Generated classes target Java 21 bytecode.
  ///
  /// @param schema the JTD schema as a parsed [JsonValue]
  /// @return a reusable [JtdValidator] backed by generated bytecode
  /// @throws IllegalArgumentException if the schema is invalid per RFC 8927
  static JtdValidator compileGenerated(JsonValue schema) {
    Objects.requireNonNull(schema, "schema must not be null");
    return JtdCodegen.compile(schema);
  }
}
