name: Secrets Self-Check

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Print SHA256 of Central creds and GPG secrets
        env:
          CENTRAL_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
          CENTRAL_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_KEYNAME: ${{ secrets.GPG_KEYNAME }}
        run: |
          set -euo pipefail
          creds_hash=$(printf "%s:%s" "$CENTRAL_USERNAME" "$CENTRAL_PASSWORD" | sha256sum | awk '{print $1}')
          pass_hash=$(printf "%s" "$GPG_PASSPHRASE" | sha256sum | awk '{print $1}')
          keyname_hash=$(printf "%s" "$GPG_KEYNAME" | sha256sum | awk '{print $1}')
          # Normalize multi-line private key before hashing
          priv_hash=$(printf "%s" "$GPG_PRIVATE_KEY" | sha256sum | awk '{print $1}')
          echo "SHA256 central(user:pass): $creds_hash"
          echo "SHA256 gpg.passphrase: $pass_hash"
          echo "SHA256 gpg.keyname(fingerprint): $keyname_hash"
          echo "SHA256 armored private key: $priv_hash"

