name: Test Issue Creation

on:
  workflow_dispatch:  # Manual trigger only for testing

permissions:
  issues: write
  contents: read

jobs:
  test-issue-creation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Test issue creation
      uses: actions/github-script@v7
      with:
        script: |
          const title = 'Test issue creation permissions';
          const body = `This is a test issue to verify GitHub Actions has permission to create issues.
          
          Created at: ${new Date().toISOString()}
          Run ID: ${{ github.run_id }}
          
          If you see this issue, the permissions are working correctly.`;
          
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: title,
            body: body,
            labels: ['test', 'github-actions']
          });